### ISSUE TITLE
System.IO.IOException: The process cannot access the file

### ISSUE THREAD

**Issue by Bluscream** [sackerud/tailDotNet#2]
# Current behaviour
```
C:\Users\blusc>tail "Launch.log"
An unexpected exception occured. Stack trace:
System.IO.IOException: The process cannot access the file 'Launch.log' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.ReadLines(String path)
   at tailDotNet.FileTailSpitter.SetStreamPosition(FileWatchConfiguration conf)
   at tailDotNet.FileTailSpitter.GetLastLinesFromFile(FileWatchConfiguration conf)
   at tailDotNet.Console.Program.Main(String[] args)
```

**Comment by Bluscream** [comment]
Maybe https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream.unlock?redirectedfrom=MSDN&view=net-5.0#System_IO_FileStream_Unlock_System_Int64_System_Int64_ can help somehow.

Or if that doesn't help there will be no way around checking the file for size changes and copying the file into a unlocked file in a loop or smth

**Comment by sackerud** [comment]
I can't reproduce this. Any tips? What application locked `Launch.log`?

**Comment by Bluscream** [comment]
A game called black squad

**Comment by koliyo** [comment]
Same problem here, with Unity player log.

```
tail -f .\Player.log
An unexpected exception occured. Stack trace:
System.IO.IOException: The process cannot access the file 'C:\Users\nilsh\AppData\LocalLow\Vixel\Vrex\Player.log' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.ReadLines(String path)
   at tailDotNet.FileTailSpitter.SetStreamPosition(FileWatchConfiguration conf)
   at tailDotNet.FileTailSpitter.GetLastLinesFromFile(FileWatchConfiguration conf)
   at tailDotNet.Console.Program.Main(String[] args)
Terminating...
```

**Comment by koliyo** [comment]
I am not very familiar with Windows specific behavior, but at least I know it is possible. This small powershell function does work

```ps1
function tail {
  if ($args.Count -eq 0) {
    Write-Error "Usage: tail <file> [lines]"
    return
  }

  $file = $args[0]
  $lines = if ($args.Count -gt 1) { $args[1] } else { 50 }

  Get-Content -Path $file -Tail $lines -Wait
}
```
